# Generated by Django 4.2.7 on 2023-12-01 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_link',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AddField(
            model_name='product',
            name='upload_product',
            field=models.FileField(default=None, upload_to='products_model/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='products_img/'),
        ),
    ]
